# fly.toml app configuration file generated for hot-daddy-bot on 2025-07-04T20:37:05+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hot-daddy-bot'
primary_region = 'syd'

[build]

[[mounts]]
  source = "hotdaddy_data"
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[[services]]
  processes = ['app']
  protocol = 'tcp'
  internal_port = 8080 # The port our health checker in index.js is listening on
  
  # These lines keep it online 24/7
  auto_stop_machines = false
  min_machines_running = 1

  # NEW: This block tells Fly.io how to check if the bot is healthy.
  # This satisfies the new requirement from the warning.
  [[services.tcp_checks]]
    interval = '15s'    # How often to check
    timeout = '2s'      # How long to wait for a response
    grace_period = '30s'# How long to wait after a machine starts before checking

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DATABASE_PATH = "/data/hot-daddy.db"

# This defines your main 'app' process, which is your bot.
# Because there is no [http_service] section, Fly treats this as a 
# long-running service that should not be shut down automatically.
[processes]
  app = "npm start"
